### ISSUE TITLE
Icon and tab name

### ISSUE THREAD

**Issue by b4rlw** [joshmedeski/tmux-nerd-font-window-name#2]
Is it possible to configure this plugin to show both the nerd font icon *and* the name of the tab simultaneously?

**Comment by joshmedeski** [comment]
Yep, good idea! I can work on it this week and I'll ping you to help me test it out.

---

As a user, I want to configure my tmux window names to show both nerd font icons and names.

- [x] Add `tmux-nerd-font-window-name-show-name` to customize the output

**Comment by joshmedeski** [comment]
@b4rlw I merged the feature and made a release explaining it, check it out and let me know if you have any feedback.

https://github.com/joshmedeski/tmux-nerd-font-window-name/releases/tag/v1.1.0

**Comment by b4rlw** [comment]
@joshmedeski
You've outdone yourself once again good sir!
Much obliged.
![terminal](https://user-images.githubusercontent.com/47506872/226486607-e5b1b57e-6276-4211-9f31-41f3d8a04a62.png)
