### ISSUE TITLE
Show warning on install/update if a dependency is missing

### ISSUE THREAD

**Issue by zatchheems** [joshmedeski/tmux-nerd-font-window-name#24]
After updating this plugin locally, windows were blank instead of being renamed properly:

<img width="358" alt="image" src="https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/8506829/9d8307bb-e5d0-422f-91e6-4e9f308ea070">

I'd assumed I'd broken my config weeks ago and never looked into it, but after looking through the updated files I noticed I was missing `yq`.

Users should see some visual feedback that dependencies are missing. This can be an error emitted to `stderr`, a warning or fallback behavior in the window bar, etc.

Is it possible to emit a warning on install/update if dependencies are missing?

```bash
if [[ ! $(which yq) ]]; then
  # Set a flag, emit an error, do something to let the user know something's up
fi
```

**Comment by zatchheems** [comment]
love the new YAML config by the way! much cleaner than the individual vars approach I had a hand in a few months back 🙁

**Comment by joshmedeski** [comment]
Thanks! I think the yaml approach is more simple.

I like your idea, I had thought about it already. Do you want to make a PR? Otherwise I can get to it later this week.

**Comment by zatchheems** [comment]
I should have some time today to take a look! the only tricky part is just finding where to put this such that it is really in the user's face. might be good to show it on tmux session start using hooks.

thinking of something like the following in case other plugins are required later then doing a `for command in [commands]; which $(command); append missing commands to new array`:

```
Error: the following dependencies are required for tmux-nerd-font-window-name to work properly:
   - tpm
   - yq

Please ensure all dependencies are installed correctly.
```

**Comment by joshmedeski** [comment]
There are some options for displaying the message:
1. A tmux popup displaying the message
2. Using `tmux display-message` (although that message goes away)
3. Just a simple "echo" would overwrite the screen until the user presses escape

**Comment by joshmedeski** [comment]
I don't think tpm is necessary, because you can't load the code before installing it.

**Comment by zatchheems** [comment]
> I don't think tpm is necessary, because you can't load the code before installing it.

right yeah, I realized after I included it it wasn't necessary. I'll see what works best!
