### ISSUE TITLE
Comillas en el nombre. 

### ISSUE THREAD

**Issue by Nefasque** [joshmedeski/tmux-nerd-font-window-name#28]
![2023-11-15-13:41:29-screenshot_000](https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/137726764/31f90965-142a-4eeb-884d-cdcbb5e9ba28)
I installed the plugin but the name appears surrounded by quotes ". Any solution?

**Comment by joshmedeski** [comment]
Did you add a custom config? If so can you share it here?

**Comment by Nefasque** [comment]
Regarding the plugin, I have not made any configuration with it as default. but this is my configuration for the status bar. maybe you help.
![2023-11-15-13:58:38-screenshot](https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/137726764/f80408fc-3987-4635-a9a4-a433a0df81f5)

**Comment by joshmedeski** [comment]
Please share what version of bash is on your machine (`bash --version`) and what version of tmux (`tmux -V`).

And what terminal emulator are you using?

**Comment by Nefasque** [comment]
tmux : 3.3
bash : 5.2.15
terminal emulator : qterminal 1.4.0 

I don't know if it is the incompatibility of versions but.
The solution I found is that the in tmux-nerd-font-window-name.sh 
line : 14 - 16 
         16 - 37
         15 - 29
where you get the icon, add the -r option and remove the quotes that apparently were left  over. With that the quotes around the icons disappeared.

![2023-11-15-16:13:48-screenshot](https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/137726764/13f12c3a-ea11-4514-818f-78875ec40113)


Also in the deafault.yml options, remove the properties that contain scripts and replace them with the camel-case.

because with - the value true was not obtained. and it failed to show the name, or rather it did not show it.
![2023-11-15-16:33:08-screenshot](https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/137726764/946efcc8-7031-4b8c-bbb6-4a6c95bf9d81)

TODO FUNCIONA !!! 
talve esto solo sea en mi caso. pero bueno comporato mi solucions. con el iconos. 

With the multi-panel icons, I don't know what to do with that. the truth.

**Comment by joshmedeski** [comment]
I'm using yq version v4.35.2

Maybe you're using an older version that can't interpret the `-` symbol? I don't want to make a breaking change on the config unless absolutely necessary.

**Comment by Nefasque** [comment]
It is possible that this is the problem. First of all, I installed yq from the repository and it installed version 3.2.3

**Comment by joshmedeski** [comment]
Please let me know if the latest version of yq fixes all your issues, hopefully it does 🤞

**Comment by Nefasque** [comment]
deberias especificar en el README las versiones nesaria. thenk for the help

**Comment by joshmedeski** [comment]
Great idea, I'll update it now. Thanks for working with me through this!
