### ISSUE TITLE
Don't showing tmux-nerd-font-window-name

### ISSUE THREAD

**Issue by yanic0de** [joshmedeski/tmux-nerd-font-window-name#31]
Hello, Josh! I have some issue with displaying your amazing plugin. After update with YAML config.

<img width="1728" alt="Снимок экрана 2023-11-27 в 23 37 22" src="https://github.com/joshmedeski/tmux-nerd-font-window-name/assets/144359981/67b97ed1-b3d5-49ab-a8c1-90cc8ff8b940">

**### this is my tmux config**
`set-option -g default-shell /opt/homebrew/bin/fish

setw -q -g utf8 on

set-option -g default-terminal "screen-256color"

set -g prefix C-a

bind s choose-tree -sZ -O name

set -g base-index 1
setw -g pane-base-index 3

setw -g automatic-rename on

set -g renumber-windows on

set -g set-titles on

unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

unbind r
bind r source-file ~/.config/tmux/tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r h resize-pane -L 5
bind -r l resize-pane -R 5

bind -r m resize-pane -Z

bind-key x kill-pane # skip "kill-pane 1? (y/n)" prompt (cmd+w)

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

unbind -T copy-mode-vi MouseDragEnd1Pane

color_bg="#2e323b"
color_fg="#282c34"
color_green="#98c379"
color_yellow="#e5c07b"
color_red="#e06c75"
color_blue="#61afef"
color_cyan="#56b6c2"
color_purple="#c678dd"
color_gray="#5c6370"
color_buffer="#939aa3"
color_selection="#3e4452"

#################################### PLUGINS ###################################

set -g @mode_indicator_prefix_prompt "WAIT"
set -g @mode_indicator_prefix_mode_style fg=$color_blue,bold
set -g @mode_indicator_copy_prompt "COPY"
set -g @mode_indicator_copy_mode_style fg=$color_green,bold
set -g @mode_indicator_sync_prompt "SYNC"
set -g @mode_indicator_sync_mode_style fg=$color_red,bold
set -g @mode_indicator_empty_prompt "TMUX"
set -g @mode_indicator_empty_mode_style fg=$color_purple,bold

set -g @route_to_ping "vultr.net"   # Use a UK based site to ping
set -g @online_icon "#[fg=$color_gray]"
set -g @offline_icon "#[fg=$color_red]"

set -g @pomodoro_on " | #[fg=$color_gray] "
set -g @pomodoro_complete " | #[fg=$color_green] "

#################################### OPTIONS ###################################

set -g status on
set -g status-position top
set -g status-left-length 200
set -g status-right-length 200
set -g set-clipboard on       # use system clipboard
set -g status-interval 2      # update status every 2 seconds
set-option -g status-style bg=default

set -g message-style bg=$color_blue,fg=$color_bg
set-window-option -g mode-style bg=$color_purple,fg=$color_bg

set -g @plugin 'tmux-plugins/tpm'                   # Plugin Manager
set -g @plugin 'tmux-plugins/tmux-sensible'         # Sensible defaults
set -g @plugin 'tmux-plugins/tmux-open'             # Open links from tmux - Select path and press o
set -g @plugin 'tmux-plugins/tmux-yank'             # Copy to system clipboard
set -g @plugin 'olimorris/tmux-pomodoro-plus'       # Pomodoro timer in tmux
set -g @plugin 'tmux-plugins/tmux-resurrect'        # Restore tmux sessions
set -g @plugin 'MunifTanjim/tmux-mode-indicator'    # Display current tmux mode
set -g @plugin 'tmux-plugins/tmux-online-status'    # Are we connected to the internet?!
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'sainnhe/tmux-fzf'                   # fzf in tmux
set -g @plugin 'tmux-plugins/tmux-continuum'        # Continuous saving of tmux environment 
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

## Plugin options
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'
set -g @pomodoro_notifications 'on'                 # Enable desktop notifications
set -g @pomodoro_sound 'Pop'                        # Sound for desktop notifications (Run `ls /System/Library/Sounds` for all sounds)
set -g @pomodoro_mins 25
set -g @pomodoro_break_mins 5
set -g @yank_with_mouse on                          # Just select with the mouse to copy

#################################### FORMAT ####################################
set -g status-left "#{tmux_mode_indicator}"
set -g status-left-length 300            # increase length (from 10)
set -g status-justify centre
set -g status-position top
set -g status-right "#{online_status} #[fg=$color_gray]%R#{pomodoro_status}"

run '~/.config/tmux/plugins/tpm/tpm'
`

**### This is my nerd font plugin**

`config:
  fallback-icon: "?" # show when no definition is found
  multi-pane-icon: "" # show when window has multiple panes (blank by default)
  show-name: true # show the window name with the icon (defaults to false)
  icon-position: "left" # show the icon to the "left" or "right" of the window name (defaults to left)

icons:
  zsh: "" # overwrite with your own symbol (Nerd Font icon, emoji, whatever!)
  cmatrix: "🤯" # add new entries that aren't included
`

**Comment by joshmedeski** [comment]
Make sure you have the latest version of [yq](https://github.com/mikefarah/yq) installed

**Comment by yanic0de** [comment]
@joshmedeski Yep, now its work! Thank u very much!

**Comment by joshmedeski** [comment]
You're welcome, glad we git it fixed for you!

**Comment by stepanzak** [comment]
For anyone using Arch: the right package is `go-yq`, not `yq`.
