### ISSUE TITLE
`icon-position: "right"` not respected

### ISSUE THREAD

**Issue by stefanlogue** [joshmedeski/tmux-nerd-font-window-name#32]
After setting `icon-position: "right"` in my config, I expect to see the icon to the left of the window name. Instead, I continue to see the icon to the right of the name. Is there anything else I should be doing to get this to work? I've tried sourcing my tmux config

**Comment by joshmedeski** [comment]
Are you updated to the latest version, you can run `<prefix>U` to update.

**Comment by stefanlogue** [comment]
Ah I assumed `<prefix>I` would grab the latest versions of plugins, thanks for this!
