### ISSUE TITLE
Small formatting issue with window-status-format and yq

### ISSUE THREAD

**Issue by Ericrulec** [joshmedeski/tmux-nerd-font-window-name#34]
Using the plugin along with this formatting
```tmux
set -g window-status-current-format ' #[fg=yellow,bold]#I #W'
set -g window-status-format " #[fg=gray,dim]#I #W"
```
gives me the correct icons, but enclosed around the icons are quotation marks `{index} "{icon}"`. 

Very aesthetically distracting.

The quick and hacky solution is editing the last line in `tmux-nerd-font-window-name/bin/tmux-nerd-font-window-name` to
```tmux
echo "$ICON" | sed 's/"//g'
```
The culprit might be `yq`, but unsure. For reference I have yq version.
```bash
> yq --version
yq 3.2.3
```

**Comment by joshmedeski** [comment]
Yes, the requirements for the plugin are yq 4 or greater, update it and let me know if it's working.

**Comment by Ericrulec** [comment]
Really sorry, I boldly assumed I had the latest version, but did not realize the Arch linux package is called `go-yq` and not `yq` (which is pre v4). It works as intended now.

**Comment by joshmedeski** [comment]
No problem, this is related https://github.com/joshmedeski/tmux-nerd-font-window-name/issues/31#issuecomment-1892757552
