### ISSUE TITLE
yq missing although it's installed?

### ISSUE THREAD

**Issue by mrt181** [joshmedeski/tmux-nerd-font-window-name#39]
I have installed yq
```bash
sudo snap install yq
```

But i still get
![grafik](https://github.com/user-attachments/assets/5ce016e6-e723-46b9-a1cd-95003ae87faa)

I also added a symlink
```bash
ln -s /snap/yq/current/bin/yq ~/.local/bin/yq
```
But that also did not help

```
>>> ~ >>> which yq
/home/martin/.local/bin/yq

>>> ~ >>> yq --version
yq (https://github.com/mikefarah/yq/) version v4.44.2

```

**Comment by joshmedeski** [comment]
Please add this to your `~/.bashrc` file and try again:

```sh
export PATH="$PATH:~/.local/bin"
```

**Comment by mrt181** [comment]
Ok tried that but does not work
![grafik](https://github.com/user-attachments/assets/f8249831-ba5e-4fd2-8475-0f4e3aa5c491)

**Comment by joshmedeski** [comment]
Did you try restarting your computer? Maybe the tmux server is missing something.

**Comment by mrt181** [comment]
I tried 
```bash
tmux kill-server & tmux
```
and also
```pwsh
wsl --shutdown
```

but the problem persists

**Comment by mrt181** [comment]
I also switched to bash directly and execute the check in your code
![grafik](https://github.com/user-attachments/assets/dea1bfc1-6cfd-4fa7-9fc9-cb1330a947fb)

**Comment by joshmedeski** [comment]
What version of bash are you on? I suspect it's an older version of bash and the if statement is incompatible.

I recommend updating to a newer version of bash and trying again.

**Comment by mrt181** [comment]
This is my bash version
```bash
> bash --version
GNU bash, version 5.2.21(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by mrt181** [comment]
running your script directly works
```bash
>…/tmux-nerd-font-window-name/bin > ./tmux-nerd-font-window-name fish 0
 fish

>…/tmux-nerd-font-window-name/bin > ./tmux-nerd-font-window-name nvim 0
 nvim
```

**Comment by joshmedeski** [comment]
I did some additional research and I'm currently stumped. I'm guessing it has something to do with WSL and PATH resolution from inside TMUX.

I typically see Ubuntu and apt-get being used in WSL, since you're using snap perhaps there's something missing. Perhaps you can manually change the line of code that calls yq to verify that it's a path issue.

```diff
-if ! command -v yq >/dev/null 2>&1; then
+if ! command -v /home/martin/.local/bin/yq >/dev/null 2>&1; then
```

I understand this isn't a good permanent solution, but hopefully it can isolate the issue. Please let me know if you're able to figure out what it is and I can potentially update the README to warn people about certain environments.

**Comment by mrt181** [comment]
ok, I did this
```diff
-if ! command -v yq >/dev/null 2>&1; then
+if ! command -v $HOME/.local/bin/yq >/dev/null 2>&1; then
```

This gets rid of the missing message but now the window name and icon are missing
![grafik](https://github.com/user-attachments/assets/6f3a4cda-b38e-4657-937c-d0d1cdc4117c)

**Comment by mrt181** [comment]
I am using
 * tmux 3.4
 * fish 3.7.1
 * bash 5.2.21
 * wsl 2.2.4.0
 * Windows Terminal 1.20.11781.0

I also tried on my linux box and there it also does not work out-of-the-box.
I had to add a symbolic link to the snap yq app to make it work on linux.

The `yq` intallation notes tell me to use `snap` for linux/ubuntu

**Comment by mrt181** [comment]
On my windows machine, I have installed yq by downloading it to `usr/bin`.
This makes it work.

snap seems to messing it up somehow.

**Comment by joshmedeski** [comment]
Glad it's working!
