### ISSUE TITLE
windows information not update without any input

### ISSUE THREAD

**Issue by mrt181** [joshmedeski/tmux-nerd-font-window-name#40]
When I start from this view
![grafik](https://github.com/user-attachments/assets/5ae7e260-5165-4e83-a0ee-b73e548a222a)

and start bash for example, the window is not updated
![grafik](https://github.com/user-attachments/assets/42cd61ac-89e1-4c46-9eac-c6b826cc4e81)
I first have to enter any key like space, up, enter etc.
![grafik](https://github.com/user-attachments/assets/464ac695-a783-4833-b093-9776ee3961ba)
When I exit bash (C-d) it updates back to fish.
![grafik](https://github.com/user-attachments/assets/663560c7-84aa-49f9-8ff4-8e3eb76e8180)
When I start nvim or lazygit it updates.
![grafik](https://github.com/user-attachments/assets/97a25696-ea1f-4e6f-8f00-bc5e29a46bbd)
![grafik](https://github.com/user-attachments/assets/9c206c92-bdf0-4d71-aecb-f160ea9185c6)
But when I exit nvim it does not update to fish until I enter any key again.
![grafik](https://github.com/user-attachments/assets/2bac7782-07db-441f-b340-25ffd3093626)
![grafik](https://github.com/user-attachments/assets/486bdd1c-84ff-40db-8a5b-72274e98e7ec)

**Comment by joshmedeski** [comment]
This is just the lifecycle of tmux and how this feature works.

I've experimented with getting it to update sooner and couldn't find a good solution.
