### ISSUE TITLE
Colored Icons?

### ISSUE THREAD

**Issue by crates51** [joshmedeski/tmux-nerd-font-window-name#48]
Hello

I've checked your video and in there every icon has a distinct color, how did you do it?

Thanks !

**Comment by joshmedeski** [comment]
You can set different colors for the current window and all other windows, this is how mine is set up.

```sh
set -g window-status-current-format '*#[fg=magenta]#W'
set -g window-status-format ' #[fg=gray]#W'
```

At this time, distinct colors per icon isn't supported.
