### ISSUE TITLE
Spacing / Sizing issue

### ISSUE THREAD

**Issue by tlvenn** [joshmedeski/tmux-nerd-font-window-name#6]
Hi @joshmedeski,

For some weird reason, I experience weird spacing issues and sizing:
![image](https://user-images.githubusercontent.com/3340262/227977441-bfac828e-be3a-42c2-b821-c85f34aab3ec.png)

Would you happen to have an idea of what the issue might be ?

**Comment by joshmedeski** [comment]
From my experience so far, the font you choose and the terminal emulator you're using impacts how nerd fonts are rendered. Let me know the terminal emulator and font choice and I can give you more clarity on that.

If you want a space between gitmux and tmux windows I recommend [adding a trailing space to your gitmux config layout](https://github.com/joshmedeski/dotfiles/blob/fd5fffc3a30fa853897f23678c1275e17d2e74b0/.config/tmux/gitmux.conf#L35).

Hope that helps.

**Comment by tlvenn** [comment]
Hi @joshmedeski, thansk a lot for the feedback and i should take a moment to thank you for your videos on Tmux  Nvim and your dotfiles, I learned a lot and very much like your aesthetic approach.

Regarding the problem at hand, I am using  kitty with the JetBrainsMono NF
![image](https://user-images.githubusercontent.com/3340262/228100934-3d5009b2-16fa-4de1-ae29-9b96ca9c6e07.png)

I have also tried Alacritty with the NF font you are using and had the same issue.

![image](https://user-images.githubusercontent.com/3340262/228101387-dee4f5fa-e6a3-4c88-98ec-4de3077c279f.png)
![image](https://user-images.githubusercontent.com/3340262/228101274-424b82e3-2d41-4a13-8583-e55dfa4a9788.png)

**Comment by tlvenn** [comment]
By the way, wanted to ask, what program are you using to generate those ascii arts and which font is that ?
![image](https://user-images.githubusercontent.com/3340262/228101627-204440ac-e018-4274-9de9-1dc1a216645c.png)

**Comment by tlvenn** [comment]
Ha figured out the ascii arts: https://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=GITMUX 😅

**Comment by joshmedeski** [comment]
Have you tried updating your gitmux layout to this?

```
  layout: [branch, divergence, flags, stats, ' ']
```

You'll also want to make sure you've updated gitmux to the latest version.

**Comment by tlvenn** [comment]
I have updated the gitmux layout and it did fix the space between gitmux and tmux windows but there are 2 remaining issues:
- Gitmux icon and related number are too much spaced, does not create a cohesive group
- Tmux icons are too small

![image](https://user-images.githubusercontent.com/3340262/228406395-29beeadd-f5c1-4427-aa21-d61e24ceec03.png)
 
Shouldn't the icons occupy the whole height like the ones from Gitmux & the Branch icon ?

**Comment by joshmedeski** [comment]
You an remove the extra space in your `gitmux.conf` file to see if that affects the sizing.

I'm not really sure what else to offer besides changing your font.

**Comment by tlvenn** [comment]
Switching to SFMono Nerd Font does solve the icon size issue, I though I tested that before and it did not matter...
In any case, thanks again for your help.

**Comment by joshmedeski** [comment]
You're welcome @tlvenn! Feel free to open another issue if you have feature requests or any other bugs come up.

**Comment by tlvenn** [comment]
For reference, with SFMono Nerd Font:
![image](https://user-images.githubusercontent.com/3340262/228720399-bc7358f8-a411-48fa-b2f4-be786ff55d90.png)
