### ISSUE TITLE
Default icon when show-name is enabled

### ISSUE THREAD

**Issue by joshmedeski** [joshmedeski/tmux-nerd-font-window-name#7]
As a user, I want a fallback icon to be shown when there is not icon matching the process name and I have `tmux-nerd-font-window-name-show-name` enabled.

Right now, this looks buggy because it lists the same process twice. I think a default `?` type icon would work well for now until #5 is implemented.

**Comment by joshmedeski** [comment]
@b4rlw what do you think of a "?" icon as the default? I was also thinking a circle icon.

**Comment by b4rlw** [comment]
Seems like a good option to me!

**Comment by b4rlw** [comment]
Either that or a blank character, but that might be confusing
